server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
db:
  database: hm-cart
  port: 3306
swagger:
  title: "黑马商场购物车服务接口文档"
  package: com.hmall.carts.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true